# Generated by Django 3.0.5 on 2020-04-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Enter your name')),
                ('mobil_phone', models.CharField(max_length=20, verbose_name='Enter your phone')),
                ('city', models.CharField(max_length=128, verbose_name='Enter your city')),
                ('team', models.CharField(max_length=128, verbose_name='Enter your team')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('answer', models.CharField(max_length=128)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('correct', models.BooleanField(default='False')),
                ('winner', models.BooleanField(default='False')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegbot.Player')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegbot.Question')),
            ],
        ),
    ]
