# Generated by Django 3.0.5 on 2020-04-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_response',
            name='correct',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='player_response',
            name='winner',
            field=models.BooleanField(default='False'),
        ),
    ]
